# Generated by Django 4.2.1 on 2025-10-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('outbound', 'Outbound'), ('return', 'Return')], default='outbound', max_length=10),
        ),
    ]
